// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEKwPG8whlQUFVuLUhbf4VNR-1WUgvZ6g',
    appId: '1:201540801531:web:bb89a0219845ed289bb15e',
    messagingSenderId: '201540801531',
    projectId: 'islamic-app-ed1ed',
    authDomain: 'islamic-app-ed1ed.firebaseapp.com',
    storageBucket: 'islamic-app-ed1ed.firebasestorage.app',
    measurementId: 'G-MCTWR213TD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_hHQB35pKOLA1ZwzaXC-UX-c6hurTSWM',
    appId: '1:201540801531:android:af0ce5ba36ca65389bb15e',
    messagingSenderId: '201540801531',
    projectId: 'islamic-app-ed1ed',
    storageBucket: 'islamic-app-ed1ed.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkGkKnWxyjJJ4olXyvwNhslMJ8mmuzYDs',
    appId: '1:201540801531:ios:c5966a11536f5d169bb15e',
    messagingSenderId: '201540801531',
    projectId: 'islamic-app-ed1ed',
    storageBucket: 'islamic-app-ed1ed.firebasestorage.app',
    androidClientId: '201540801531-ok8k3odn48vk5kdp237549mcmt0jsdoh.apps.googleusercontent.com',
    iosClientId: '201540801531-m3ddi1dnntb75qcqrtea4sgvtb9fpi5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.islamicApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkGkKnWxyjJJ4olXyvwNhslMJ8mmuzYDs',
    appId: '1:201540801531:ios:c5966a11536f5d169bb15e',
    messagingSenderId: '201540801531',
    projectId: 'islamic-app-ed1ed',
    storageBucket: 'islamic-app-ed1ed.firebasestorage.app',
    androidClientId: '201540801531-ok8k3odn48vk5kdp237549mcmt0jsdoh.apps.googleusercontent.com',
    iosClientId: '201540801531-m3ddi1dnntb75qcqrtea4sgvtb9fpi5t.apps.googleusercontent.com',
    iosBundleId: 'com.example.islamicApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAEKwPG8whlQUFVuLUhbf4VNR-1WUgvZ6g',
    appId: '1:201540801531:web:28cf4f841f916a509bb15e',
    messagingSenderId: '201540801531',
    projectId: 'islamic-app-ed1ed',
    authDomain: 'islamic-app-ed1ed.firebaseapp.com',
    storageBucket: 'islamic-app-ed1ed.firebasestorage.app',
    measurementId: 'G-2N2MF98XM3',
  );
}
